spring:
  profiles:
    active: production
  application:
    name: MeetUp
  datasource:
    url: jdbc:postgresql://salt.db.elephantsql.com/cpoomlzp
    password: QCwd3DcEysPt0euG0gTZyVGbJ6sEGcbP
    username: cpoomlzp
    continue-on-error: false
    schema: classpath:sql/Schema.sql
    initialization-mode: never

server:
  port: ${PORT:9990}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full