spring:
  profiles:
    active: production
  application:
    name: MeetUp

server:
  port: ${PORT:9990}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full