spring:
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: production
  application:
    name: MeetUp
  datasource:
#     Heroku DB
    url: jdbc:postgresql://ec2-174-129-205-197.compute-1.amazonaws.com:5432/d132n30cpecl80
    username: yakgmstslqpheb
    password: 5a687df146eae7b0b542f05365922b15134492c2468a85686c3bba2ce7a00584
    # local DB (Julia)
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: user
    # local DB (Polina)
#    url: jdbc:postgresql://localhost:5432/meetup
#    username: postgres
#    password: root
    # local DB (Oleg)
#    url: jdbc:postgresql://localhost:5432/meetup
#    username: postgres
#    password: ggwp

    hikari:
      maximumPoolSize: 7

    #    for local Postgres db(julia)
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: user

    #    for local Postgres db(polina)
    #    url: jdbc:postgresql://localhost:5432/meetup
    #    username: postgres
    #    password: root

    #for H2 DB
    #datasource:
    #  url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    #  password:
    #  username: sa
    continue-on-error: false
    schema: classpath:sql/Schema.sql
    #    driver-class-name: org.h2.Driver
    #    initialization-mode: always
    #  h2:
    #   console:
    #    enabled: true
    #   path: /h2
    driver-class-name: org.postgresql.Driver


server:
  port: ${PORT:9990}
