spring:
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: production
  application:
    name: MeetUp
  datasource:
    # for Heroku DB
    url: jdbc:postgresql://ec2-54-197-238-238.compute-1.amazonaws.com:5432/dc72m1l1vrrhs0
    username: hwfgkkvlxomhnc
    password: c2757e017c207706006d9a70475719a4404a5019f12d19ce9e728a1cf5619f4b
    hikari:
      maximumPoolSize: 5

#    for local Postgres db(julia)
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: user

#    for local Postgres db(polina)
#    url: jdbc:postgresql://localhost:5432/meetup
#    username: postgres
#    password: root

    #for H2 DB
    #datasource:
    #  url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    #  password:
    #  username: sa
    continue-on-error: false
    schema: classpath:sql/Schema.sql
    #    driver-class-name: org.h2.Driver
    #    initialization-mode: always
    #  h2:
    #   console:
    #    enabled: true
    #   path: /h2
    driver-class-name: org.postgresql.Driver


server:
  port: ${PORT:9990}

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full