package com.meetup.utils;

import java.util.prefs.AbstractPreferences;

public enum DbQueryConstants {

    id_author,
    id_title,
    contents,
    time_posted,
    id,
    id_article,
    id_topic,
    name,
    script,
    user_id,
    id_speaker,
    id_user,
    id_language,
    id_state,
    title,
    read,
    start_time,
    duration_minutes,
    min_attendees,
    max_attendees,
    description,
    meetup_id,
    id_meetup,
    text,
    usId,
    roleId,
    login,
    first_name,
    last_name,
    about,
    email,
    password,
    language_ids,
    roles,
    login_param,
    user_id_param,
    reason,
    id_destination,
    id_source,
    id_speak,
    speaker_id_param,
    id_param,
    active,
    rate,
    num_rates,
    message,
    type,
    time_created,
    id_type,
    count,
    offset,
    limit;
}
